# Generated by Django 3.0.14 on 2023-08-26 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutaArchivo', models.ImageField(blank=True, null=True, upload_to='archivos_excel/')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEstado', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Libreto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniLibreto', models.TextField()),
                ('salLibreto', models.TextField()),
                ('atrLibreto', models.TextField()),
                ('finLibreto', models.TextField()),
                ('terLibreto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSituacion', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SituacionFechasTitulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTitulacion', models.DateTimeField()),
                ('fechaTitulacionEstado', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomTipo', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutUsuario', models.TextField(max_length=12)),
                ('nomUsuario', models.TextField(max_length=20)),
                ('apeUsuario', models.TextField(max_length=20)),
                ('pasUsuario', models.TextField(max_length=20)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulacion.Estado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulacion.Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Titulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=12)),
                ('nombre', models.TextField(max_length=50)),
                ('paterno', models.TextField(max_length=50)),
                ('materno', models.TextField(max_length=50)),
                ('carrera', models.TextField(max_length=100)),
                ('mencion', models.TextField(max_length=50)),
                ('sigla', models.TextField(max_length=50)),
                ('fechaTitulacion', models.DateTimeField()),
                ('yearTitulacion', models.IntegerField()),
                ('ninvitados', models.IntegerField(null=True)),
                ('areaAcademica', models.TextField(max_length=255)),
                ('situacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='titulacion.Situacion')),
            ],
        ),
    ]
